steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-run', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/react-run', 'npm', 'run', 'test', '--', '--coverage']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-run']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'react-run', '--image', 'gcr.io/$PROJECT_ID/react-run', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images:
- gcr.io/$PROJECT_ID/react-run


